### ISSUE TITLE
Having a gravedigger ?

### ISSUE THREAD

**Issue by dav-m85** [scheb/tombstone#1]
Hi @scheb, first let me tell you this is a really fine piece of software, really love the idea.

I'm going to run tombstone on a set of production servers, and I'm thinking about how to generate reports efficiently. My problem is that the analyzer need both the log and the sources to be executed, making me checking out the code on the same machine as the analyzer.

I think it could be avoided by creating a "gravedigger" command which detects tombstones and send them in the log. This simplifies usage, I just need to run the gravedigger on each deploy instead of having to setup a specific build job (not impossible, but gosh I'm lazy).

Do you think it is feasible ?

**Comment by scheb** [comment]
Hi, thanks for the feedback.

So you would like to extract all the tombstones from the source in the deployment process and write the information (file, location, values) to some log file. Then, you can download all the logs (invocation logs and extracted tombstones), run the analyzer on it and get a result. Did I get that right?

Basically it would work, but there is a major drawback. You can only generate a textual report from it. That's ok when you have just a few tombstones, but the more you have, the more you need the HTML report. And the HTML requires the source, otherwise it can't generate a proper report where you can browse the source, as seen here: http://www.christianscheb.de/wp-content/uploads/2015/09/tombstone-report.jpg

In addition you'd need the tombstone-analyzer as a dependency in production, which introduces a bunch of unnecessary dependencies. Well, they are necessary, but only once when the tombstones are extracted from the source on the production server.

Altogether, it makes analysis a little bit simpler, but at the cost of loosing a important feature (in my opinion) and project cleanliness.

The intended way to do it would be - sorry ;) - a build job. Add tombstone-analyzer as a "dev" dependency to the project. Create a build job in your CI server, which does the following things:

- Check out source
- Install dependencies along with "dev" ones
- Get logs from production servers
- Run analyzer
- Optional: Publish HTML report
